/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface CrowdfactoryInterface extends utils.Interface {
  functions: {
    "createProject(string,string,uint256,uint64[8],uint128[8],address)": FunctionFragment;
    "feePercentageAmount()": FunctionFragment;
    "feeWalletAddr()": FunctionFragment;
    "publishedProjs(uint256)": FunctionFragment;
    "totalPublishedProjs()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createProject"
      | "feePercentageAmount"
      | "feeWalletAddr"
      | "publishedProjs"
      | "totalPublishedProjs"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createProject",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "feePercentageAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeWalletAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishedProjs",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPublishedProjs",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feePercentageAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeWalletAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishedProjs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPublishedProjs",
    data: BytesLike
  ): Result;

  events: {
    "ProjectCreated(string,uint256,address,address,address,uint256,uint64[8],uint128[8])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProjectCreated"): EventFragment;
}

export interface ProjectCreatedEventObject {
  projTitle: string;
  goalAmount: BigNumber;
  ownerWalletAddr: string;
  projAddress: string;
  feeWalletAddr: string;
  timestamp: BigNumber;
  stockPerTier: BigNumber[];
  costPerTier: BigNumber[];
}
export type ProjectCreatedEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    BigNumber[],
    BigNumber[]
  ],
  ProjectCreatedEventObject
>;

export type ProjectCreatedEventFilter = TypedEventFilter<ProjectCreatedEvent>;

export interface Crowdfactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CrowdfactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createProject(
      projectTitle: PromiseOrValue<string>,
      projDescript: PromiseOrValue<string>,
      projGoalAmount: PromiseOrValue<BigNumberish>,
      stockPerTier_: PromiseOrValue<BigNumberish>[],
      costPerTier_: PromiseOrValue<BigNumberish>[],
      projOwnerAddr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feePercentageAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    feeWalletAddr(overrides?: CallOverrides): Promise<[string]>;

    publishedProjs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    totalPublishedProjs(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  createProject(
    projectTitle: PromiseOrValue<string>,
    projDescript: PromiseOrValue<string>,
    projGoalAmount: PromiseOrValue<BigNumberish>,
    stockPerTier_: PromiseOrValue<BigNumberish>[],
    costPerTier_: PromiseOrValue<BigNumberish>[],
    projOwnerAddr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feePercentageAmount(overrides?: CallOverrides): Promise<BigNumber>;

  feeWalletAddr(overrides?: CallOverrides): Promise<string>;

  publishedProjs(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  totalPublishedProjs(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    createProject(
      projectTitle: PromiseOrValue<string>,
      projDescript: PromiseOrValue<string>,
      projGoalAmount: PromiseOrValue<BigNumberish>,
      stockPerTier_: PromiseOrValue<BigNumberish>[],
      costPerTier_: PromiseOrValue<BigNumberish>[],
      projOwnerAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    feePercentageAmount(overrides?: CallOverrides): Promise<BigNumber>;

    feeWalletAddr(overrides?: CallOverrides): Promise<string>;

    publishedProjs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    totalPublishedProjs(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "ProjectCreated(string,uint256,address,address,address,uint256,uint64[8],uint128[8])"(
      projTitle?: null,
      goalAmount?: null,
      ownerWalletAddr?: PromiseOrValue<string> | null,
      projAddress?: null,
      feeWalletAddr?: null,
      timestamp?: PromiseOrValue<BigNumberish> | null,
      stockPerTier?: null,
      costPerTier?: null
    ): ProjectCreatedEventFilter;
    ProjectCreated(
      projTitle?: null,
      goalAmount?: null,
      ownerWalletAddr?: PromiseOrValue<string> | null,
      projAddress?: null,
      feeWalletAddr?: null,
      timestamp?: PromiseOrValue<BigNumberish> | null,
      stockPerTier?: null,
      costPerTier?: null
    ): ProjectCreatedEventFilter;
  };

  estimateGas: {
    createProject(
      projectTitle: PromiseOrValue<string>,
      projDescript: PromiseOrValue<string>,
      projGoalAmount: PromiseOrValue<BigNumberish>,
      stockPerTier_: PromiseOrValue<BigNumberish>[],
      costPerTier_: PromiseOrValue<BigNumberish>[],
      projOwnerAddr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feePercentageAmount(overrides?: CallOverrides): Promise<BigNumber>;

    feeWalletAddr(overrides?: CallOverrides): Promise<BigNumber>;

    publishedProjs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalPublishedProjs(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createProject(
      projectTitle: PromiseOrValue<string>,
      projDescript: PromiseOrValue<string>,
      projGoalAmount: PromiseOrValue<BigNumberish>,
      stockPerTier_: PromiseOrValue<BigNumberish>[],
      costPerTier_: PromiseOrValue<BigNumberish>[],
      projOwnerAddr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feePercentageAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    feeWalletAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publishedProjs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalPublishedProjs(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
